services:
  # postgres
  postgres:
    image: docker.io/postgres:17-alpine
    healthcheck:
      test: pg_isready -q -t 2 -d $$POSTGRES_DB -U $$POSTGRES_USER
      start_period: 20s
      timeout: 30s
      interval: 10s
      retries: 5
    environment:
      - POSTGRES_DB=netbox
      - POSTGRES_USER=netbox
      - POSTGRES_PASSWORD=J5brHrAXFLQSif0K
    volumes:
      - netbox-postgres-data:/var/lib/postgresql/data
    ports: 
      - 5432:5432

  # redis
  redis:
    image: docker.io/valkey/valkey:8.0-alpine
    volumes:
      - netbox-redis-data:/data
    ports: 
      - 6379:6379
  redis-cache:
    image: docker.io/valkey/valkey:8.0-alpine
    volumes:
      - netbox-redis-cache-data:/data
    ports: 
      - 6380:6379

volumes:
  netbox-postgres-data:
    driver: local
  netbox-redis-data:
    driver: local
  netbox-redis-cache-data:
    driver: local